name: e2e workflow

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches: [ main ]

  workflow_dispatch:
      inputs:
        scriptName:
          description: 'Name of the script to run'
          required: false
          default: 'test-sequential-e2e'

        dockerImage:
          description: 'identifier, ie runId or sha'
          required: false
          default: 'latest'
      # For manually trigger
 

jobs:
  test:
    name: Test code quality and run tests
    runs-on: ubuntu-latest
    env:
      API_URL: 'ws://172.16.238.10:9944'
      TEST_PALLET_ADDRESS: ${{ secrets.TEST_PALLET_ADDRESS }}
      E2E_XYK_PALLET_ADDRESS: ${{ secrets.E2E_XYK_PALLET_ADDRESS }}
      E2E_TREASURY_PALLET_ADDRESS: ${{ secrets.E2E_TREASURY_PALLET_ADDRESS }}
      TEST_SUDO_NAME: ${{ secrets.TEST_SUDO_NAME }}
      TEST_SCRIPT: 'test-sequential-e2e'
      MANGATA_NODE_VERSION: 'latest'
    steps:
      - name: Set variables
        run:  |
          echo "TEST_SCRIPT=${{ github.event.inputs.scriptName || env.TEST_SCRIPT }}" >> $GITHUB_ENV
          echo "MANGATA_NODE_VERSION=${{ github.event.inputs.dockerImage || env.MANGATA_NODE_VERSION }}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Tsc code quality check
        run: yarn tsc-lint --skipLibCheck
      - name: ESLint code quality check
        run: yarn eslint
      - name: Start mangata-node node
        run: docker-compose -f devops/dockerfiles/node-build/docker-compose.yml up -d
      - name: Docker ps
        run: docker ps
      - name: Sleep for 5 seconds
        run: sleep 5s #we need to sleep to avoid block Number 0.
        shell: bash
      - name: Run e2e tests
        run: yarn ${{ env.TEST_SCRIPT }}
      
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: JEST Tests            # Name of the check run which will be created
          path: reports/jest-*.xml    # Path to test results
          reporter: jest-junit        # Format of test results

      - name: Archive report files
        uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: TestReport
          path: reports/html-report/report.html

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: feature/gh-pages-for-e2e-test-report
          path: gh-pages
          repository: mangata-finance/mangata-node

      - name: Generate Allure Report [History]
        uses: simple-elf/allure-report-action@master
        if: always()
        #id: allure-report
        with:
          allure_results: allure-results
          #gh_pages: feature/gh-pages-for-e2e-test-report
          #allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20
          github_repo: mangata-finance/mangata-node

      - name: Generate Allure Report [Deploy to GH]
        if: always()
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          deploy_key: ${{ secrets.PUSH_GH_PAGE_TOKEN }}
          external_repository: mangata-finance/mangata-node
          personal_token: ${{ secrets.PUSH_GH_PAGE_TOKEN }}
          publish_dir: allure-history
          publish_branch: feature/gh-pages-for-e2e-test-report

      - name: Stop Containers
        if: always()
        run: docker-compose -f "devops/dockerfiles/docker-compose.yml" down
