name: e2e workflow

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches: [ main ]

  workflow_dispatch:
      inputs:
        scriptName:
          description: 'Name of the script to run'
          required: false
          default: 'test-sequential-e2e'

        dockerImage:
          description: 'identifier, ie runId or sha'
          required: false
          default: 'latest'
      # For manually trigger
 

jobs:
  test:
    name: Test code quality and run tests
    runs-on: ubuntu-latest
    env:
      API_URL: 'ws://172.16.238.10:9944'
      TEST_PALLET_ADDRESS: ${{ secrets.TEST_PALLET_ADDRESS }}
      E2E_XYK_PALLET_ADDRESS: ${{ secrets.E2E_XYK_PALLET_ADDRESS }}
      E2E_TREASURY_PALLET_ADDRESS: ${{ secrets.E2E_TREASURY_PALLET_ADDRESS }}
      E2E_TREASURY_BURN_PALLET_ADDRESS : ${{ secrets.E2E_TREASURY_BURN_PALLET_ADDRESS }}
      TEST_SUDO_NAME: ${{ secrets.TEST_SUDO_NAME }}
      TEST_SCRIPT: 'test-sequential-e2e'
      MANGATA_NODE_VERSION: 'latest'
    steps:
      - name: Set variables
        run:  |
          echo "TEST_SCRIPT=${{ github.event.inputs.scriptName || env.TEST_SCRIPT }}" >> $GITHUB_ENV
          echo "MANGATA_NODE_VERSION=${{ github.event.inputs.dockerImage || env.MANGATA_NODE_VERSION }}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Tsc code quality check
        run: yarn tsc-lint --skipLibCheck
      - name: ESLint code quality check
        run: yarn eslint
